name: Psalm

on:
  push:
    branches: [master]
    paths:
      - '**.php'
      - 'psalm*'
  pull_request:
    paths:
      - '**.php'
      - 'psalm*'

concurrency:
  group: psalm-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  psalm:
    name: psalm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.json') }}

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Run Psalm
        if: github.event_name == 'pull_request'
        run: composer psalm

      - name: Run Psalm and report type coverage
        if: github.event_name != 'pull_request'
        run: composer psalm:ci
